version: '3.5'
services:

  django_center_waf:
    container_name: django_center_waf-docker        # 指定容器的名称
    build:
      context: ../
      dockerfile: compose/django/Dockerfile
    command:
      - sh
      - -c
      - |
        nohup python ./task_main.py &
        uwsgi --ini uwsgi.ini
        /bin/bash -c " while true; do sleep 1; done"
    # command: uwsgi --ini uwsgi.ini
        # python manage.py runserver 0:6988
    environment:
      TZ : 'Asia/Shanghai'
    env_file:
      - ./.env
    volumes:
      - ../:/app:rw
    ports:
      - "6988:6988"
    restart: always

networks:
  default:
    external:
      name: my-server-network

# docker ps -a | grep "Exited" | awk '{print $1 }'|xargs docker stop
# docker ps -a | grep "Exited" | awk '{print $1 }'|xargs docker rm
# docker images|grep none|awk '{print $3 }'|xargs docker rmi

# docker rmi $(docker images -q | awk '/^<none>/ { print $3 }')


# docker exec -it django_my_tool-docker /bin/bash