env: 
  'debug'

redis_db: redis://redis_back_db:6479/10

redis_client:
  - redis://redis_back_db:6479/0
  - redis://redis_back_db:6479/1

task_redis:
  -
    host: redis_back_db
    port: 6479
    db: 15